# Python
from pathlib import Path
from dataclasses import dataclass, field


# 3rd Party


# 1st Party
from .lyric_payload import LyricPayload
from ..lyric_matcher import MatchResult
from .lyric_fetcher_type import LyricFetcherType


# TODO: Explain the 3 phases the text goes through

# TODO: In the future, this dataclass should be able to house multiple lyric sources, for now, it can only manage
# one.

@dataclass
class LyricAlignTask:
    path_to_audio_file: Path
    # filename without extension
    filename: str                   = ""                            # Contained in path_to_audio_file, mostly for convenience / debugging
    artist: str                     = ""
    song_name: str                  = ""

    # Fetch-related lyric properties
    lyric_payload: LyricPayload     = field(default_factory=LyricPayload)

    # Alignment-related lyric properties
    lyric_text_expanded: str        = ""                            # Detected and replaced {xxxx|4} with xxxx xxxx xxxx xxxx
    lyric_lines_expanded: list[str] = field(default_factory=list)
    lyric_text_alignment_ready: str = ""                            # Lyric text more suitable for NUSAutoAlignLyrix

    lyric_fetcher_type_source: LyricFetcherType  = LyricFetcherType.Disabled # Local .txt, Genius DB, or other source

    # Whether [8x], [16x], (4x) or (10x) is in the raw lyrics - actually {} I think...?
    detected_multiplier: bool       = False

    #lyric_validity: LyricValidity = LyricValidity.NotSet

    # A dict of the aligned lyric data (generated by convert_aligmentlyrics_to_dict())
    lyrics_aligned: dict            = field(default_factory=dict)

    match_result: MatchResult       = field(default_factory=MatchResult)


    def __post_init__(self):
        """ Parses given data into more granular data. """

        # For now we assume songs always come in this filename form: <artist> - <song name>
        # We split at " - ", as opposed to "-", because hyphens can often appear in both the artist or song name.
        filename_parts = self.path_to_audio_file.stem.split(" - ") # stem, to get file without extension

        self.filename = self.path_to_audio_file.stem

        self.artist = filename_parts[0].strip()
        self.song_name = filename_parts[1].strip()