from .lyric_fetcher_base import LyricFetcherBase
from .lyric_fetcher_disabled import LyricFetcherDisabled
from .lyric_fetcher_local_file import LyricFetcherLocalFile
from .lyric_fetcher_pypi_lyricsgenius import LyricFetcherPyPiLyricsGenius
from .lyric_fetcher_pypi_lyrics_extractor import LyricFetcherPyPiLyricsExtractor
from .lyric_fetcher_website_lyrics_dot_ovh import LyricFetcherWebsiteLyricsDotOvh